-- MySQL Script generated by MySQL Workbench
-- Mon Jan  7 15:59:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema daytrade
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema daytrade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `daytrade` DEFAULT CHARACTER SET utf8 ;
USE `daytrade` ;

-- -----------------------------------------------------
-- Table `daytrade`.`Corretora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daytrade`.`Corretora` ;

CREATE TABLE IF NOT EXISTS `daytrade`.`Corretora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cor_primaria` VARCHAR(45) NOT NULL,
  `cor_secundaria` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `daytrade`.`Ordem_Original`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daytrade`.`Ordem_Original` ;

CREATE TABLE IF NOT EXISTS `daytrade`.`Ordem_Original` (
  `id` BIGINT NOT NULL,
  `pregao` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `corretora` INT NULL,
  `valor` DECIMAL NOT NULL,
  `agressor` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_OrdOrig_SaldoCo`
    FOREIGN KEY (`corretora`)
    REFERENCES `daytrade`.`Corretora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_OrdOrig_SaldoCo_idx` ON `daytrade`.`Ordem_Original` (`corretora` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `daytrade`.`Saldo_Corretora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daytrade`.`Saldo_Corretora` ;

CREATE TABLE IF NOT EXISTS `daytrade`.`Saldo_Corretora` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `pregao` DATE NOT NULL,
  `corretora` INT NOT NULL,
  `volume_financeiro` BIGINT NOT NULL,
  `volume_quantidade` BIGINT NOT NULL,
  `media` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_SaldoCo_Corretora`
    FOREIGN KEY (`corretora`)
    REFERENCES `daytrade`.`Corretora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_SaldoCo_Corretora_idx` ON `daytrade`.`Saldo_Corretora` (`corretora` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `daytrade`.`Frequencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `daytrade`.`Frequencia` ;

CREATE TABLE IF NOT EXISTS `daytrade`.`Frequencia` (
  `pregao` DATE NOT NULL,
  `abertura` DECIMAL(7,2) NOT NULL,
  `maxima` DECIMAL(7,2) NOT NULL,
  `minima` DECIMAL(7,2) NOT NULL,
  `fechamento` DECIMAL(7,2) NOT NULL,
  `media` DECIMAL(4,2) NOT NULL,
  PRIMARY KEY (`pregao`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
